// Package gofmp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 6efb8729c49d05fcc2d90d9553b4bccb0e2e9055 DO NOT EDIT.
package gofmp

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// CompanyProfile defines model for CompanyProfile.
type CompanyProfile struct {
	Address           string             `json:"address"`
	AverageVolume     int                `json:"averageVolume"`
	Beta              float64            `json:"beta"`
	Ceo               string             `json:"ceo"`
	Change            float64            `json:"change"`
	ChangePercentage  float64            `json:"changePercentage"`
	Cik               string             `json:"cik"`
	City              string             `json:"city"`
	CompanyName       string             `json:"companyName"`
	Country           string             `json:"country"`
	Currency          string             `json:"currency"`
	Cusip             string             `json:"cusip"`
	DefaultImage      bool               `json:"defaultImage"`
	Description       string             `json:"description"`
	Exchange          string             `json:"exchange"`
	ExchangeFullName  string             `json:"exchangeFullName"`
	FullTimeEmployees string             `json:"fullTimeEmployees"`
	Image             string             `json:"image"`
	Industry          string             `json:"industry"`
	IpoDate           openapi_types.Date `json:"ipoDate"`
	IsActivelyTrading bool               `json:"isActivelyTrading"`
	IsAdr             bool               `json:"isAdr"`
	IsEtf             bool               `json:"isEtf"`
	IsFund            bool               `json:"isFund"`
	Isin              string             `json:"isin"`
	LastDividend      float64            `json:"lastDividend"`
	MarketCap         int                `json:"marketCap"`
	Phone             string             `json:"phone"`
	Price             float64            `json:"price"`
	Range             string             `json:"range"`
	Sector            string             `json:"sector"`
	State             string             `json:"state"`
	Symbol            string             `json:"symbol"`
	Volume            int                `json:"volume"`
	Website           string             `json:"website"`
	Zip               string             `json:"zip"`
}

// FinancialEstimates defines model for FinancialEstimates.
type FinancialEstimates struct {
	Date               openapi_types.Date `json:"date"`
	EbitAvg            float64            `json:"ebitAvg"`
	EbitHigh           float32            `json:"ebitHigh"`
	EbitLow            float64            `json:"ebitLow"`
	EbitdaAvg          float64            `json:"ebitdaAvg"`
	EbitdaHigh         float64            `json:"ebitdaHigh"`
	EbitdaLow          float32            `json:"ebitdaLow"`
	EpsAvg             float64            `json:"epsAvg"`
	EpsHigh            float64            `json:"epsHigh"`
	EpsLow             float64            `json:"epsLow"`
	NetIncomeAvg       float64            `json:"netIncomeAvg"`
	NetIncomeHigh      float32            `json:"netIncomeHigh"`
	NetIncomeLow       float64            `json:"netIncomeLow"`
	NumAnalystsEps     int                `json:"numAnalystsEps"`
	NumAnalystsRevenue int                `json:"numAnalystsRevenue"`
	RevenueAvg         float64            `json:"revenueAvg"`
	RevenueHigh        float64            `json:"revenueHigh"`
	RevenueLow         float64            `json:"revenueLow"`
	SgaExpenseAvg      float64            `json:"sgaExpenseAvg"`
	SgaExpenseHigh     float64            `json:"sgaExpenseHigh"`
	SgaExpenseLow      float64            `json:"sgaExpenseLow"`
	Symbol             string             `json:"symbol"`
}

// FullCandle defines model for FullCandle.
type FullCandle struct {
	Change        float64            `json:"change"`
	ChangePercent float64            `json:"changePercent"`
	Close         float64            `json:"close"`
	Date          openapi_types.Date `json:"date"`
	High          float64            `json:"high"`
	Low           float64            `json:"low"`
	Open          float64            `json:"open"`
	Symbol        string             `json:"symbol"`
	Volume        int                `json:"volume"`
	Vwap          float64            `json:"vwap"`
}

// LightCandle defines model for LightCandle.
type LightCandle struct {
	Date   openapi_types.Date `json:"date"`
	Price  float32            `json:"price"`
	Symbol string             `json:"symbol"`
	Volume int                `json:"volume"`
}

// News defines model for News.
type News struct {
	Action          string    `json:"action"`
	GradingCompany  string    `json:"gradingCompany"`
	NewGrade        string    `json:"newGrade"`
	NewsBaseURL     string    `json:"newsBaseURL"`
	NewsPublisher   string    `json:"newsPublisher"`
	NewsTitle       string    `json:"newsTitle"`
	NewsURL         string    `json:"newsURL"`
	PreviousGrade   string    `json:"previousGrade"`
	PriceWhenPosted float32   `json:"priceWhenPosted"`
	PublishedDate   time.Time `json:"publishedDate"`
	Symbol          string    `json:"symbol"`
}

// SearchSymbol defines model for SearchSymbol.
type SearchSymbol struct {
	Currency         string `json:"currency"`
	Exchange         string `json:"exchange"`
	ExchangeFullName string `json:"exchangeFullName"`
	Name             string `json:"name"`
	Symbol           string `json:"symbol"`
}

// GetAnalystEstimatesParams defines parameters for GetAnalystEstimates.
type GetAnalystEstimatesParams struct {
	Symbol string `form:"symbol" json:"symbol"`
	Period string `form:"period" json:"period"`
	Page   *int   `form:"page,omitempty" json:"page,omitempty"`
	Limit  *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetGradesLatestNewsParams defines parameters for GetGradesLatestNews.
type GetGradesLatestNewsParams struct {
	Page  *int `form:"page,omitempty" json:"page,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetHistoricalPriceEodFullParams defines parameters for GetHistoricalPriceEodFull.
type GetHistoricalPriceEodFullParams struct {
	Symbol string              `form:"symbol" json:"symbol"`
	From   *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To     *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// GetHistoricalPriceEodLightParams defines parameters for GetHistoricalPriceEodLight.
type GetHistoricalPriceEodLightParams struct {
	Symbol string              `form:"symbol" json:"symbol"`
	From   *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To     *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// GetProfileParams defines parameters for GetProfile.
type GetProfileParams struct {
	Symbol string `form:"symbol" json:"symbol"`
}

// GetRatingsSnapshotParams defines parameters for GetRatingsSnapshot.
type GetRatingsSnapshotParams struct {
	Symbol string `form:"symbol" json:"symbol"`
	Limit  *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetSearchNameParams defines parameters for GetSearchName.
type GetSearchNameParams struct {
	SearchSymbol string  `form:"search-symbol" json:"search-symbol"`
	Limit        *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Exchange     *string `form:"exchange,omitempty" json:"exchange,omitempty"`
}

// GetSearchSymbolParams defines parameters for GetSearchSymbol.
type GetSearchSymbolParams struct {
	SearchSymbol string `form:"search-symbol" json:"search-symbol"`
}

type OperationPath string

const (

	// /analyst-estimates
	GetAnalystEstimatesOperationPath OperationPath = "/analyst-estimates"

	// /grades-latest-news
	GetGradesLatestNewsOperationPath OperationPath = "/grades-latest-news"

	// /historical-price-eod/full
	GetHistoricalPriceEodFullOperationPath OperationPath = "/historical-price-eod/full"

	// /historical-price-eod/light
	GetHistoricalPriceEodLightOperationPath OperationPath = "/historical-price-eod/light"

	// /profile
	GetProfileOperationPath OperationPath = "/profile"

	// /ratings-snapshot
	GetRatingsSnapshotOperationPath OperationPath = "/ratings-snapshot"

	// /search-name
	GetSearchNameOperationPath OperationPath = "/search-name"

	// /search-symbol
	GetSearchSymbolOperationPath OperationPath = "/search-symbol"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAnalystEstimates request
	GetAnalystEstimates(ctx context.Context, params *GetAnalystEstimatesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGradesLatestNews request
	GetGradesLatestNews(ctx context.Context, params *GetGradesLatestNewsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHistoricalPriceEodFull request
	GetHistoricalPriceEodFull(ctx context.Context, params *GetHistoricalPriceEodFullParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHistoricalPriceEodLight request
	GetHistoricalPriceEodLight(ctx context.Context, params *GetHistoricalPriceEodLightParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProfile request
	GetProfile(ctx context.Context, params *GetProfileParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRatingsSnapshot request
	GetRatingsSnapshot(ctx context.Context, params *GetRatingsSnapshotParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSearchName request
	GetSearchName(ctx context.Context, params *GetSearchNameParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSearchSymbol request
	GetSearchSymbol(ctx context.Context, params *GetSearchSymbolParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAnalystEstimates(ctx context.Context, params *GetAnalystEstimatesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAnalystEstimatesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetGradesLatestNews(ctx context.Context, params *GetGradesLatestNewsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGradesLatestNewsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHistoricalPriceEodFull(ctx context.Context, params *GetHistoricalPriceEodFullParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHistoricalPriceEodFullRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHistoricalPriceEodLight(ctx context.Context, params *GetHistoricalPriceEodLightParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHistoricalPriceEodLightRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProfile(ctx context.Context, params *GetProfileParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProfileRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRatingsSnapshot(ctx context.Context, params *GetRatingsSnapshotParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRatingsSnapshotRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSearchName(ctx context.Context, params *GetSearchNameParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSearchNameRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSearchSymbol(ctx context.Context, params *GetSearchSymbolParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSearchSymbolRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAnalystEstimatesRequest generates requests for GetAnalystEstimates
func NewGetAnalystEstimatesRequest(server string, params *GetAnalystEstimatesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/analyst-estimates")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "symbol", runtime.ParamLocationQuery, params.Symbol); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "period", runtime.ParamLocationQuery, params.Period); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetGradesLatestNewsRequest generates requests for GetGradesLatestNews
func NewGetGradesLatestNewsRequest(server string, params *GetGradesLatestNewsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/grades-latest-news")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHistoricalPriceEodFullRequest generates requests for GetHistoricalPriceEodFull
func NewGetHistoricalPriceEodFullRequest(server string, params *GetHistoricalPriceEodFullParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/historical-price-eod/full")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "symbol", runtime.ParamLocationQuery, params.Symbol); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.From != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "from", runtime.ParamLocationQuery, *params.From); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.To != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "to", runtime.ParamLocationQuery, *params.To); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHistoricalPriceEodLightRequest generates requests for GetHistoricalPriceEodLight
func NewGetHistoricalPriceEodLightRequest(server string, params *GetHistoricalPriceEodLightParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/historical-price-eod/light")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "symbol", runtime.ParamLocationQuery, params.Symbol); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.From != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "from", runtime.ParamLocationQuery, *params.From); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.To != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "to", runtime.ParamLocationQuery, *params.To); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetProfileRequest generates requests for GetProfile
func NewGetProfileRequest(server string, params *GetProfileParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/profile")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "symbol", runtime.ParamLocationQuery, params.Symbol); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetRatingsSnapshotRequest generates requests for GetRatingsSnapshot
func NewGetRatingsSnapshotRequest(server string, params *GetRatingsSnapshotParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ratings-snapshot")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "symbol", runtime.ParamLocationQuery, params.Symbol); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSearchNameRequest generates requests for GetSearchName
func NewGetSearchNameRequest(server string, params *GetSearchNameParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/search-name")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "search-symbol", runtime.ParamLocationQuery, params.SearchSymbol); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Exchange != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "exchange", runtime.ParamLocationQuery, *params.Exchange); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSearchSymbolRequest generates requests for GetSearchSymbol
func NewGetSearchSymbolRequest(server string, params *GetSearchSymbolParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/search-symbol")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "search-symbol", runtime.ParamLocationQuery, params.SearchSymbol); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAnalystEstimatesWithResponse request
	GetAnalystEstimatesWithResponse(ctx context.Context, params *GetAnalystEstimatesParams, reqEditors ...RequestEditorFn) (*GetAnalystEstimatesClientResponse, error)

	// GetGradesLatestNewsWithResponse request
	GetGradesLatestNewsWithResponse(ctx context.Context, params *GetGradesLatestNewsParams, reqEditors ...RequestEditorFn) (*GetGradesLatestNewsClientResponse, error)

	// GetHistoricalPriceEodFullWithResponse request
	GetHistoricalPriceEodFullWithResponse(ctx context.Context, params *GetHistoricalPriceEodFullParams, reqEditors ...RequestEditorFn) (*GetHistoricalPriceEodFullClientResponse, error)

	// GetHistoricalPriceEodLightWithResponse request
	GetHistoricalPriceEodLightWithResponse(ctx context.Context, params *GetHistoricalPriceEodLightParams, reqEditors ...RequestEditorFn) (*GetHistoricalPriceEodLightClientResponse, error)

	// GetProfileWithResponse request
	GetProfileWithResponse(ctx context.Context, params *GetProfileParams, reqEditors ...RequestEditorFn) (*GetProfileClientResponse, error)

	// GetRatingsSnapshotWithResponse request
	GetRatingsSnapshotWithResponse(ctx context.Context, params *GetRatingsSnapshotParams, reqEditors ...RequestEditorFn) (*GetRatingsSnapshotClientResponse, error)

	// GetSearchNameWithResponse request
	GetSearchNameWithResponse(ctx context.Context, params *GetSearchNameParams, reqEditors ...RequestEditorFn) (*GetSearchNameClientResponse, error)

	// GetSearchSymbolWithResponse request
	GetSearchSymbolWithResponse(ctx context.Context, params *GetSearchSymbolParams, reqEditors ...RequestEditorFn) (*GetSearchSymbolClientResponse, error)
}

type GetAnalystEstimatesClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]FinancialEstimates
}

// Status returns HTTPResponse.Status
func (r GetAnalystEstimatesClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAnalystEstimatesClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetGradesLatestNewsClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]News
}

// Status returns HTTPResponse.Status
func (r GetGradesLatestNewsClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGradesLatestNewsClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHistoricalPriceEodFullClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]FullCandle
}

// Status returns HTTPResponse.Status
func (r GetHistoricalPriceEodFullClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHistoricalPriceEodFullClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHistoricalPriceEodLightClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]LightCandle
}

// Status returns HTTPResponse.Status
func (r GetHistoricalPriceEodLightClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHistoricalPriceEodLightClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProfileClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]CompanyProfile
}

// Status returns HTTPResponse.Status
func (r GetProfileClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProfileClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRatingsSnapshotClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
}

// Status returns HTTPResponse.Status
func (r GetRatingsSnapshotClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRatingsSnapshotClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSearchNameClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]SearchSymbol
}

// Status returns HTTPResponse.Status
func (r GetSearchNameClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSearchNameClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSearchSymbolClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]SearchSymbol
}

// Status returns HTTPResponse.Status
func (r GetSearchSymbolClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSearchSymbolClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetAnalystEstimatesWithResponse request returning *GetAnalystEstimatesClientResponse
func (c *ClientWithResponses) GetAnalystEstimatesWithResponse(ctx context.Context, params *GetAnalystEstimatesParams, reqEditors ...RequestEditorFn) (*GetAnalystEstimatesClientResponse, error) {
	rsp, err := c.GetAnalystEstimates(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAnalystEstimatesClientResponse(rsp)
}

// GetGradesLatestNewsWithResponse request returning *GetGradesLatestNewsClientResponse
func (c *ClientWithResponses) GetGradesLatestNewsWithResponse(ctx context.Context, params *GetGradesLatestNewsParams, reqEditors ...RequestEditorFn) (*GetGradesLatestNewsClientResponse, error) {
	rsp, err := c.GetGradesLatestNews(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGradesLatestNewsClientResponse(rsp)
}

// GetHistoricalPriceEodFullWithResponse request returning *GetHistoricalPriceEodFullClientResponse
func (c *ClientWithResponses) GetHistoricalPriceEodFullWithResponse(ctx context.Context, params *GetHistoricalPriceEodFullParams, reqEditors ...RequestEditorFn) (*GetHistoricalPriceEodFullClientResponse, error) {
	rsp, err := c.GetHistoricalPriceEodFull(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHistoricalPriceEodFullClientResponse(rsp)
}

// GetHistoricalPriceEodLightWithResponse request returning *GetHistoricalPriceEodLightClientResponse
func (c *ClientWithResponses) GetHistoricalPriceEodLightWithResponse(ctx context.Context, params *GetHistoricalPriceEodLightParams, reqEditors ...RequestEditorFn) (*GetHistoricalPriceEodLightClientResponse, error) {
	rsp, err := c.GetHistoricalPriceEodLight(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHistoricalPriceEodLightClientResponse(rsp)
}

// GetProfileWithResponse request returning *GetProfileClientResponse
func (c *ClientWithResponses) GetProfileWithResponse(ctx context.Context, params *GetProfileParams, reqEditors ...RequestEditorFn) (*GetProfileClientResponse, error) {
	rsp, err := c.GetProfile(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProfileClientResponse(rsp)
}

// GetRatingsSnapshotWithResponse request returning *GetRatingsSnapshotClientResponse
func (c *ClientWithResponses) GetRatingsSnapshotWithResponse(ctx context.Context, params *GetRatingsSnapshotParams, reqEditors ...RequestEditorFn) (*GetRatingsSnapshotClientResponse, error) {
	rsp, err := c.GetRatingsSnapshot(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRatingsSnapshotClientResponse(rsp)
}

// GetSearchNameWithResponse request returning *GetSearchNameClientResponse
func (c *ClientWithResponses) GetSearchNameWithResponse(ctx context.Context, params *GetSearchNameParams, reqEditors ...RequestEditorFn) (*GetSearchNameClientResponse, error) {
	rsp, err := c.GetSearchName(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSearchNameClientResponse(rsp)
}

// GetSearchSymbolWithResponse request returning *GetSearchSymbolClientResponse
func (c *ClientWithResponses) GetSearchSymbolWithResponse(ctx context.Context, params *GetSearchSymbolParams, reqEditors ...RequestEditorFn) (*GetSearchSymbolClientResponse, error) {
	rsp, err := c.GetSearchSymbol(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSearchSymbolClientResponse(rsp)
}

// ParseGetAnalystEstimatesClientResponse parses an HTTP response from a GetAnalystEstimatesWithResponse call
func ParseGetAnalystEstimatesClientResponse(rsp *http.Response) (*GetAnalystEstimatesClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAnalystEstimatesClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []FinancialEstimates
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetGradesLatestNewsClientResponse parses an HTTP response from a GetGradesLatestNewsWithResponse call
func ParseGetGradesLatestNewsClientResponse(rsp *http.Response) (*GetGradesLatestNewsClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGradesLatestNewsClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []News
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHistoricalPriceEodFullClientResponse parses an HTTP response from a GetHistoricalPriceEodFullWithResponse call
func ParseGetHistoricalPriceEodFullClientResponse(rsp *http.Response) (*GetHistoricalPriceEodFullClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHistoricalPriceEodFullClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []FullCandle
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHistoricalPriceEodLightClientResponse parses an HTTP response from a GetHistoricalPriceEodLightWithResponse call
func ParseGetHistoricalPriceEodLightClientResponse(rsp *http.Response) (*GetHistoricalPriceEodLightClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHistoricalPriceEodLightClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []LightCandle
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetProfileClientResponse parses an HTTP response from a GetProfileWithResponse call
func ParseGetProfileClientResponse(rsp *http.Response) (*GetProfileClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProfileClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []CompanyProfile
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetRatingsSnapshotClientResponse parses an HTTP response from a GetRatingsSnapshotWithResponse call
func ParseGetRatingsSnapshotClientResponse(rsp *http.Response) (*GetRatingsSnapshotClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRatingsSnapshotClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetSearchNameClientResponse parses an HTTP response from a GetSearchNameWithResponse call
func ParseGetSearchNameClientResponse(rsp *http.Response) (*GetSearchNameClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSearchNameClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []SearchSymbol
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetSearchSymbolClientResponse parses an HTTP response from a GetSearchSymbolWithResponse call
func ParseGetSearchSymbolClientResponse(rsp *http.Response) (*GetSearchSymbolClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSearchSymbolClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []SearchSymbol
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaX5OjNhL/KiruHpIqgwGDbZwnZ2Z2M3eziS8zydZdah9kaBtlhUQkYcdJzXe/EmCb",
	"P/IEXzaTuqt7c5nupv/+utXiVyvmWc4ZMCWtxa+WjFPIcPnzhmc5ZoeV4BtCQf+TC56DUATK5zhJBMjy",
	"J/yMs1zTWN8wQMs8p4BWWHxE7/HBGlnqkOtnUgnCttbzyMI7EHgL33NaZNASELph4Lvh/MREmIItCM21",
	"BoVbxJ7jByNrw0WGlbWwEl6sKZzfx4psXXHGwNtqvhMOeiIZV+kB3TrohvOPJj3jFLNtW8HAmUXD3lny",
	"rkDEwBTuSPEdz3Xnw+SQj23dXdd1J77rRROjykQd2vQ3RRk0xo3kVZC/xp04WFUQ71nsmNkKpkTnRd89",
	"GkkLIYDFPdpbM7EkecfcyWw+mXiua6JPYIMLqu6zroM3mEo4Maw5p4BZxSFjQXJFOLtkMEpAki2TI5Rh",
	"VmxwrAoBcoQwS1CGxUdQEskMC5WnnOkHOQjJGaZIe7NQIOQIKbymoOQI7QEL/bsWgOMYpOSCgER7Lmiy",
	"Jwk46CkFVMcC8c0GhERkpcWPEEaUMEB803zpF+gdjpvP+jp8gcgKJ02arKCK2Hkhci7hqOEXpVoNLVOe",
	"QV9XLVYQSdgWLYlY8USO6kJ/+v746z1WcTpCXwJWEuWCJ0WsarO/4hmseOKge4UwlVw/3pEEZMV6gwUg",
	"WeQ5F6qkjykvEiRB7EgMtY4afLACiXZYEF5IlFOsdAXJESIspkWitVNpiUDoUXEBSKVYv5DyPYoLqXim",
	"Pas4SoiM+c5xjNkNPxsK3/p6+Xi7/MdL9G8KSvuVVPGht5SvMUWPQCFWJimbgtInksFdllN+AOggqzcN",
	"XHMRkF72W6lSuVyMx+Uj6WwIwywmmGY8AUrYNheQOzHPxvKQrTkdL5erBydnW6N4lhSyV+w3nMkiA4Hu",
	"tD2CMxJLI3fOb7HqqOdFc9f2fNvzrSYGajqTCLmMFdkBPTwJrGPcEqZEYSx0IpeJGIYJRN6pzVDSNwVL",
	"htIS1kW9E5qFJkspluqW6LrovMN1omFdp8KnG9wG0UnounN/4vm6d5haawkqbV0/C9z55yiKprbnesa8",
	"ywWJO21t4jvDupro15c3DRx3bvtT1/FMr5MQK96OqPUEcco45VvjmCFVL/NulkbCsgo6/WC5ejDR7vpD",
	"i9Gle1hLoi7U5X6/d7AGPl2Eprf80m2DUeh6QZ9SuxJ+KoiAxFr8cDTkGJtmPtTzUyfJjpE4zTqGweVk",
	"c3dwa48PjVZfTS11BRy7ugEnG1DbwJmz79rtuprjTolwnkJM2HnM6dFpTq1no2NaVD4+oucZqDpDxREd",
	"TDB0BJkTLHw4xYevf9Qw/zyy3hyx904qkun+1R+lk16e+q4f2W5k+/MhCAlropa7Ni56gTv150Hg+dFs",
	"UElqIV+RbWqQEs6n82B2geeB7w0sfhTOguEvTnBP/zCMQn/iz4JgeoWYvgWlnGA+n4fXyOlZVYrxplN3",
	"MjUx5bJrQORMh2Eh5LKvtev4rhcMFtBVN3Lc0B14OmKg7lnMM+inUOSF7iSMpm50nSRDFGbePJzM/Chy",
	"X2LsuX0SBcE0Cmcz1xumQpEtGaYHqeRd3h6hpiaYbtB/CztgRbsQPSOTqCi7/grmEzeauG7VZYd0wUpO",
	"z1uVoPBqQV3vlXL8K+TILb77OQcme7ZNvGkUTOfh1JteKalnXSlq5s0D/1qluvZVSoX+3POHSRrc5y/1",
	"1RqBG/5uR7GVG00saeFTE/POINqA4DOkd2qjW2Od6u06qxeHbohPyHWGoROeGIujV2EfdI8rKL3BLDGt",
	"iQxHqdCZXr9C6exPgmkwdBFDufxPx1RjYw5t17fdYEhjTru5708mjjcZ9G7aSXbfnzrTcBArz4F1eGfO",
	"py4R4ygcBME88nzj/m637xxL/InrzIekwm9UY2lu7ezKb8eoN0ZX83xr1WrpLH4g21RdSuPfmwkXD0uv",
	"F4Hf8OLxyFDL1B75GvaGaRXH/e1ZymliUnBbjcr1LrnN8zdn5aB3XGwxM7Ey2L8VOOl4/ZsdiD3oSF3g",
	"kV9iCd99+9BmWwP7hbAtvnTe0oyrYk2JTKFzxvyyZr3E9kQU7Si5wocVpuhJYCYrb6F3WGwJk+Uia4UP",
	"GTCFqmMUuhVkB+it4HuVjtDdASTSuVX/g94TlaJHJTjboqd3t2iZAk4Q36B7tgOpuEC3+LBANSZf0rLn",
	"keZRtOmdsR+OXX8cTIJZ6M7dcY4POab2GrCS9k+BDcdjjI2lrc4W2llloY1ZYueVhXaVS3aiLbS3pT02",
	"HEDaZfHUf+yJSm1ZGmirLGlWUyGIuZhgR3ghr86PMsffp8BWXCpo71hmM2fmh4aCzOu8SG5fwIAnL1p4",
	"84UbOK7r/quLCLYiGQzdPKz+ec1E0tbuHOxmcrYLo5vtjVLrurZXwKNj9fd9qQHjEbCI08eTUZ1R4Jqr",
	"gD9nCcuuvAj5/RMl6+1OXlqT9DcM1WasEEQdHuMUssrVy5z8HQ7LQpXjB2HWwvqpgHJXUplo4Zx8hMba",
	"DJcc1vNzufLdlBdmqoI26827FVqu7nVzACFL8LdkeX9wnDZwTqyFNXFcZ6JTA6u0VGOMK1Q6o4b+dwvl",
	"NFft8wln94m1sN6CqiHsvCjRkgTOQIGQ1uIHsyEnT57dW+2Eq7vM0o5uKMySchCEJ59EUrU66vE1erGZ",
	"kZKMqJc5P2j9ZM6ZrLzpu25ZXJypekzGeU5JXLp2/KOsWvVZIFGQlYx/FbCxFtZfxucr4HF9/zs2bK2e",
	"z6kiBK4zpXWdZi0RJVLp3lTHHZ1uHtA5A0pGhbe6DGq6EjzGGmtA2lRTKZvVw8elbCkRSj6UxOWgMihb",
	"/usjU5r6x8ciJXq0IDGmdgn0NvBkvCkofSkkX52YVprnjicaw167jDeinPHOfL8xnF+So/hVUl6nLs8n",
	"7aty4BxOdPfNLSpDihKsMPpMB/XzViLEKRYvpQEtx6ur8uChnsj+nwifKBGah9VPlQllXC+mQn7+EOhS",
	"3I/fCv1RcX4Vz3a+e7rKucdPOI6+armyHqFLZ2q/sa20JcO5TPmL1fRtRft4JH3lKnqFxtcdaV/wcO04",
	"dHLcxQ4my7OIfZzoL3m3OrLUc/YQx1ZiX9W/Fzgbl6d/cs20zn1XVUyGVZwStkVS8fhjeyCpXN2K5vm8",
	"9XI8H0/H4z8yov8Lvm2cH0sPNU+OP3zQJkoQu6P/CkEbu6MXviuqT4cfnv8dAAD//xj77n1iKgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
